### ISSUE TITLE
Cannot install appxbundle or appx files

### ISSUE THREAD

**Issue by Pysis868** [toolboc/UWPStreamer#6]
App Installer Window:
![image](https://user-images.githubusercontent.com/1408565/113324892-a5b1ef80-92e5-11eb-934f-0a19dc61d154.png)

> This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

Could not get PowerShell to do it either.
```
Add-AppxPackage : Deployment failed with HRESULT: 0x800B0109, A certificate chain processed, but
terminated in a root certificate which is not trusted by the trust provider.
error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted. NOTE: For additional information, look for [ActivityId] 4d2c28cb-2696-0002-8ecc-2f4d9626d701 in the
Event Log or use the command line Get-AppPackageLog -ActivityID 4d2c28cb-2696-0002-8ecc-2f4d9626d701
At line:1 char:1
+ Add-AppxPackage -Path ...\UWPStreamer_1.1.21.0_Test\UWPStre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (...\UW..._arm.appxbundle:String) [Add-AppxPack
   age], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppx
   PackageCommand
```

Could not get any CertUtil commands to help either..
https://social.technet.microsoft.com/Forums/en-US/c94eb4d7-7c4f-4da0-8c6e-bbec0da0e7d6/how-to-solve-error-0x800b0109
https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-troubleshoot-app-package-signature-errors?redirectedfrom=MSDN

**Comment by toolboc** [comment]
Intersting, I just installed without issue using the [store link](https://www.microsoft.com/en-us/p/uwpstreamer/9nd66p3vdnxt?activetab=pivot:overviewtab):

![image](https://user-images.githubusercontent.com/2018336/113332153-6b951d80-92e6-11eb-9d93-dc0a6312a90b.png)

Could this be a configuration setting on your machine?

**Comment by Pysis868** [comment]
It's the file from the releases page I was having trouble with.

**Comment by toolboc** [comment]
@Pysis868,

Please install from the store link in my previous comment or if you insist on generating your own self-signed .appx, please build the project from source and sign it with a trusted cert on your machine.  The .appx included in this project is signed with a foreign cert and can only be installed by allowing installation of insecure apps on your machine which is not recommended.

**Comment by Pysis868** [comment]
Building does sound like the remaining option, but I opened the issue when following the link in the readme mentioning a precompiled exe, and then seeing this release: [UWPStreamer - Input Redirection + Fullscreen (1.1.21.0)](https://github.com/toolboc/UWPStreamer/releases/tag/v1.1.21.0).  I showed in my post how I tried managing the foreign cert contained in the zip file using several methods, but none seemed to work.  The issue remains as long as that release package is available.

**Comment by toolboc** [comment]
The release version of the .appx in this repo is not recommended for foreign installation.  It’s provided as an artifact for what would be expected to be produced if you took a snapshot of the source and built the code locally.  

Due to the nature of UWP apps in general, they must go through a certification and signing process in order to be available for redistribution on machines which the original binary was not created on.  

You can statically analyze this included .appx if you are paranoid that the store release is somehow different, but I can assure you this same artifact was used as the candidate during publication to the MS Store.

**Comment by Pysis868** [comment]
Just typical to manage packages that way for me, but also curious about all available items.
Since you've explained why it's there now, it could benefit from having that description added to that release entry including that it is not meant to be installed.
